language: node_js
node_js:
  - "8.2.1"
sudo: required

services:
  - docker
  
notifications:
  email: false

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  
install:
  - npm install newman  

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - chmod +x script.sh
  - chmod +x script_run_docker.sh
  - ./script.sh

  
script:
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Inbox.postman_collection.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Study_List.postman_collection.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-DICOMweb_Capability_Tokens.postman_collection.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-proxy_pacs.postman_collection.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
