language: node_js
node_js:
  - "8.16.0"
sudo: required

services:
  - docker

notifications:
  email: false

env:
  - DOCKER_COMPOSE_VERSION=1.21.2

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

install:
  - npm install newman@3.10.0

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - ./script.sh

script:
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Album.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Study_List-withOptions.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Introspect.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Viewer_token.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-series_favorite.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Study_comments.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-keycloak.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops_Capabilities_tokens_Delete.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Capabilities_tokens_albums.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-DICOMweb_Capability_Tokens.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-DICOMweb_proxy.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Inbox.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Study_List.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-proxy_pacs.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
  - ./script_run_docker.sh
  - node_modules/.bin/newman run postman/kheops-Zipper.json -e postman/kheops_localhost.postman_environment.json -g postman/Workspace.postman_globals.json
