version: '3.1'
#https://github.com/docker-library/postgres/issues/151
services:

  ldap:
    container_name: pacsldap
    image: dcm4che/slapd-dcm4chee:${PACS_LDAP_IMAGE_TAG}
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
      - dcm4chee-ldap-ldap:/var/lib/ldap
      - dcm4chee-ldap-slapdd:/etc/ldap/slapd.d
    restart: on-failure

  db:
    container_name: db
    image: osirixfoundation/kheops-database:${KHEOPS_DATABASE_IMAGE_TAG}
    volumes:
      - kheops-db-data:/var/lib/postgresql/data
    env_file: docker-compose.env
    secrets:
      - kheops_authdb_pass
      - kheops_pacsdb_pass
    restart: on-failure

  arc:
    container_name: pacsarc
    image: osirixfoundation/kheops-dcm4chee-arc-psql:${KHEOPS_ARC_IMAGE_TAG}
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "8787:8787"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /storage /opt/wildfly/standalone
      WILDFLY_WAIT_FOR: ldap:389 db:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    secrets:
      - kheops_pacsdb_pass
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
      - dcm4chee-arc-wildfly:/opt/wildfly/standalone
      - /dcm4chee-arc/storage:/storage
    restart: on-failure

  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:${KHEOPS_AUTHORIZATION_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - db
      - arc
    secrets:
      - kheops_superuser_hmasecret
      - kheops_auth_hmasecret
      - kheops_authdb_pass
      - kheops_keycloak_clientsecret
      - kheops_client_dicomwebproxysecret
      - kheops_client_zippersecret
      - kheops_metric_ressource_password

  kheops-zipper:
    container_name: kheopszipper
    image: osirixfoundation/kheops-zipper:${KHEOPS_ZIPPER_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - arc
    secrets:
      - kheops_client_zippersecret

  kheops-ui:
    container_name: kheopsui
    image: osirixfoundation/kheops-ui:${KHEOPS_UI_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    env_file: docker-compose.env
    restart: on-failure
    depends_on:
      - kheops-authorization
      - arc

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheops-dicomweb-proxy:${KHEOPS_DICOMWEB_PROXY_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    ports:
      - "8049:8080"
    depends_on:
      - kheops-authorization
      - arc
    secrets:
      - kheops_auth_hmasecret_post
      - kheops_client_dicomwebproxysecret

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:${KHEOPS_REVERSE_PROXY_IMAGE_TAG}
    container_name: kheopsreverseproxy
    secrets:
      - privkey1.pem
      - fullchain1.pem
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    ports:
      - "80:80"
      - "443:443"
      - "8042:8042"
      - "8048:8048"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - arc
      - pacs-authorization-proxy
    extra_hosts:
      - "${ROOT_URL}:127.0.0.1"

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacs-authorization-proxy:${PACS_AUTHORIZATION_PROXY_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    ports:
      - "82:80"
    depends_on:
      - arc
    secrets:
      - kheops_auth_hmasecret
      - kheops_auth_hmasecret_post

secrets:
  kheops_authdb_pass:
    file: ${SECRETS_PATH}/kheops_authdb_pass
  kheops_pacsdb_pass:
    file: ${SECRETS_PATH}/kheops_pacsdb_pass
  kheops_superuser_hmasecret:
    file: ${SECRETS_PATH}/kheops_superuser_hmasecret
  kheops_auth_hmasecret:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret
  kheops_auth_hmasecret_post:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret_post
  privkey1.pem:
    file: ${NGINX_KEY}/privkey1.pem
  fullchain1.pem:
    file: ${NGINX_KEY}/fullchain1.pem
  kheops_keycloak_clientsecret:
    file: ${SECRETS_PATH}/kheops_keycloak_clientsecret
  kheops_client_dicomwebproxysecret:
    file: ${SECRETS_PATH}/kheops_client_dicomwebproxysecret
  kheops_client_zippersecret:
    file: ${SECRETS_PATH}/kheops_client_zippersecret
  kheops_metric_ressource_password:
    file: ${SECRETS_PATH}/kheops_metric_ressource_password

volumes:
  dcm4chee-ldap-ldap:
  dcm4chee-ldap-slapdd:
  dcm4chee-db-data:
  dcm4chee-arc-wildfly:
  kheops-db-data:
