version: "3.1"

services:

  ldap:
    container_name: pacsldap
    image: dcm4che/slapd-dcm4chee:2.4.44-13.0
#    ports:
#      - "389:389"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
      - ${DCM4CHEE_PATH}/ldap:/var/lib/ldap
      - ${DCM4CHEE_PATH}/slapd.d:/etc/ldap/slapd.d
    restart: on-failure

  db:
    container_name: pacsdb
    image: dcm4che/postgres-dcm4chee:10.0-13
#    ports:
#      - "5432:5432"
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
      - ${DCM4CHEE_PATH}/db:/var/lib/postgresql/data
    restart: on-failure

  arc:
    container_name: pacsarc
    image: dcm4che/dcm4chee-arc-psql:5.13.0
    ports:
      - "8080:8080"
      - "8443:8443"
      - "9990:9990"
      - "8787:8787"
      - "11112:11112"
      - "2575:2575"
    env_file: docker-compose.env
    environment:
      WILDFLY_CHOWN: /opt/wildfly/standalone /storage
      WILDFLY_WAIT_FOR: ldap:389 db:5432
      JAVA_OPTS: -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -agentlib:jdwp=transport=dt_socket,address=8787,server=y,suspend=n
    depends_on:
      - ldap
      - db
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
      - ${DCM4CHEE_PATH}/wildfly:/opt/wildfly/standalone
      - ${DCM4CHEE_PATH}/storage:/storage
    restart: on-failure



  kheops-authorization-database:
    container_name: kheopsauthorizationdatabase
    image: osirixfoundation/kheops-authorization-database:${KHEOPS_AUTHORIZATION_DATABASE_IMAGE_TAG}
#    ports:
#      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password
#      KHEOPS_MYSQL_USER: /run/secrets/mysql_user
#      KHEOPS_MYSQL_PASSWORD: /run/secrets/mysql_password
    secrets:
      - mysql_root_password
      - mysql_password
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
      - kheops-mysql-volume:/var/lib/mysql
    restart: on-failure



  kheops-authorization:
    container_name: kheopsauthorization
    image: osirixfoundation/kheops-authorization:${KHEOPS_AUTHORIZATION_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    depends_on:
      - kheops-authorization-database
      - arc
    secrets:
      - kheops_superuser_hmasecret
      - kheops_auth_hmasecret
      - mysql_password

  kheops-dicomweb-proxy:
    container_name: kheopsdicomwebproxy
    image: osirixfoundation/kheopsproxy-tomcat:${KHEOPS_PROXY_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    env_file: docker-compose.env
    ports:
      - "8049:8080"
    depends_on:
      - kheops-authorization
      - arc

  kheops-viewer:
    container_name: kheopsviewer
    image: osirixfoundation/kheops-viewer:${KHEOPS_VIEWER_IMAGE_TAG}
    ports:
      - "3000:3000"

    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    restart: on-failure
    secrets:
      - OAuth2_secret
    depends_on:
      - kheops-authorization
      - arc

  kheops-reverse-proxy:
    image: osirixfoundation/kheops-reverse-proxy:${KHEOPS_REVERSE_PROXY_IMAGE_TAG}
    container_name: kheopsreverseproxy
    secrets:
      - privkey1.pem
      - fullchain1.pem
    env_file: docker-compose.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    ports:
      - "80:80"
      - "443:443"
      - "8042:8042"
      - "8048:8048"
    depends_on:
      - kheops-authorization
      - kheops-dicomweb-proxy
      - arc
      - pacs-authorization-proxy

  pacs-authorization-proxy:
    container_name: pacsauthorizationproxy
    env_file: docker-compose.env
    image: osirixfoundation/pacsproxyauthorization:${KHEOPS_PROXY_PACS_IMAGE_TAG}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${TIME_ZONE}:/etc/timezone:ro
    ports:
      - "82:80"
    depends_on:
      - arc
    secrets:
      - kheops_superuser_hmasecret



secrets:
  kheops_superuser_hmasecret:
    file: ${SECRETS_PATH}/kheops_superuser_hmasecret
  kheops_auth_hmasecret:
    file: ${SECRETS_PATH}/kheops_auth_hmasecret
  mysql_root_password:
    file: ${SECRETS_PATH}/mysql_root_password
  mysql_password:
    file: ${SECRETS_PATH}/mysql_password
  privkey1.pem:
    file: ${NGINX_KEY}/privkey1.pem
  fullchain1.pem:
    file: ${NGINX_KEY}/fullchain1.pem
  OAuth2_secret:
    file: ${SECRETS_PATH}/OAuth2_secret

volumes:
  kheops-mysql-volume:
